title: "Teándrico"
logo: /imagenes/logo-teandrico4.png
description: "Un espacio dedicado a la divulgación teológica a partir de la reflexión académica."
url: "https://teandrico.com"
baseurl: ""
lang: "es"

# theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "air"

author:
  name: "Estiben Álvarez"
  bio: "Estudiante de teología en la Universidad Católica de Oriente."

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/articulos/page:num/"

permalink: /articulos/:title/

remote_theme: mmistakes/minimal-mistakes

navigation:
  main:
    - title: "Inicio"
      url: /
    - title: "Artículos"
      url: /articulos/
    - title: "Club de Lectura"
      url: /club-de-lectura/
    - title: "Sobre el proyecto"
      url: /sobre-el-proyecto/
    - title: "Contacto"
      url: /contacto/

archive:
  type: grid

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      teaser: /imagenes/articulo-henoteismo.jpg

