title: "Teándrico - Divulgación Teológica"
masthead_title: "Teándrico"
logo: /imagenes/logo-teandrico4.png
description: "Un espacio dedicado a la divulgación teológica a partir de la reflexión académica."
url: "https://teandrico.com"
baseurl: ""
lang: "es"
locale: "es-ES"
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

author:
  name: "Estiben Álvarez"
  avatar: "/imagenes/foto-estiben-alvarez2.jpg"
  bio: "Estudiante de teología en la Universidad Católica de Oriente. Fundador de Teándrico."
  location: "Colombia"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/estiben_alvarez7/"
    - label: "Correo"
      icon: "fas fa-fw fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&to=respaldo357183n+teandrico@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/articulos/page:num/"
permalink: /articulos/:title/
remote_theme: mmistakes/minimal-mistakes

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
      show_date: true
      share: false
  - scope:
      path: ""
      type: posts
    values:
      author_profile: false
      show_date: true
      share: true
      show_tags: true
      teaser: /imagenes/foto-articulo-henoteismo-2.jpg

favicon: /favicon-teandrico.png

share: true

tag_archive:
  type: liquid
  path: /tags/

search: false

authors:
  estiben-alvarez:
    name: "Estiben Álvarez"
    avatar: "/imagenes/foto-estiben-alvarez2.jpg"
    bio: "Estudiante de teología en la Universidad Católica de Oriente. Fundador de Teándrico."
    location: "Colombia"
    links:
      - label: "Instagram"
        icon: "fab fa-fw fa-instagram"
        url: "https://www.instagram.com/estiben_alvarez7/"
